sudo: false # docker-based container

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

language: python

addons:
  apt_packages:
    - swig3.0

python:
  - 3.6

scala:
  - 2.11.2

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/tmp

before_script:
  - rm -rf $HOME/tmp/*
  - wget https://github.com/sbt/sbt/releases/download/v1.0.3/sbt-1.0.3.zip -O $HOME/tmp/sbt-1.0.3.zip
  - unzip $HOME/tmp/sbt-1.0.3.zip -d $HOME/tmp
  - mkdir -p $HOME/.sbt/launchers/1.0.3/
  - ls -l $HOME/tmp/sbt/bin/
  - cp $HOME/tmp/sbt/bin/sbt-launch.jar $HOME/.sbt/launchers/1.0.3/
  - ls -l $HOME/.sbt/launchers/1.0.3/
  - pip3 install http://download.pytorch.org/whl/cpu/torch-0.3.1-cp36-cp36m-linux_x86_64.whl
  - pip3 install torchvision

script:
  - make build_compiler
  - make test
